// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorExt
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeGeneratorExt.9256973a-37e8-4dcb-b368-e9b537671f38";
        public const string Name = "CodeGeneratorExt";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
